# Generated by Django 4.2.16 on 2024-11-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_identificacion', models.CharField(max_length=45)),
                ('cli_nombre', models.CharField(max_length=100)),
                ('cli_apellido', models.CharField(max_length=100)),
                ('cli_direccion', models.CharField(max_length=80)),
                ('cli_telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_nombre', models.CharField(max_length=45)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_matricula', models.CharField(max_length=20)),
                ('veh_color', models.CharField(max_length=20)),
                ('veh_tipo', models.CharField(max_length=20)),
                ('veh_garantia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ven_identificacion', models.CharField(max_length=45)),
                ('ven_nombre', models.CharField(max_length=100)),
                ('ven_apellido', models.CharField(max_length=100)),
                ('ven_direccion', models.CharField(max_length=80)),
                ('ven_telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_nombre', models.CharField(max_length=45)),
                ('ver_potencia', models.CharField(max_length=45)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vent_fechaventa', models.DateField()),
                ('vent_precio_final', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.version'),
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai_nombre', models.CharField(max_length=45)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vendedor')),
            ],
        ),
    ]
